# This is a start-once from rancher 1.x - not even on a cron schedule
{{ if .Values.analyze.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: {{ include "gitMirror.name" . }}-analyze
    helm.sh/chart: {{ include "gitMirror.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
  name: {{ include "gitMirror.name" . }}-analyze
spec:
  replicas: {{ .Values.analyze.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "gitMirror.name" . }}-analyze
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "gitMirror.name" . }}-analyze
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      shareProcessNamespace: true
      containers:
      - name: analyze
        args:
        - -period
        - 24h
        image: {{ .Values.analyze.image.repository }}:{{ .Values.analyze.image.tag }}
        imagePullPolicy: {{ .Values.analyze.image.pullPolicy }}
        resources:
          {{ toYaml .Values.analyze.resources | nindent 10 }}
        volumeMounts:
        - mountPath: /var/log/nginx
          name: efs-shared
      restartPolicy: Always

      volumes:
      - name: efs-shared
        persistentVolumeClaim:
          claimName: efs-shared
{{ end }}
