replicaCount: 2
podAnnotations:
  prometheus.io/scrape: "true"
  prometheus.io/port: "9333"
  prometheus.io/path: "/metrics"
image:
  repository: rancher/rdns-server
  tag: v0.5.7-rancher-amd64
  pullPolicy: IfNotPresent
resources: {}
rdnsServerIngressHostname: api.on-rio.io
secret:
  name: rdnsserver
