{{- if .Values.config }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "drone-autoscaler.fullname" . }}-config
  labels:
    {{- include "drone-autoscaler.labels" . | nindent 4 }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
type: Opaque
data:
{{- if .Values.config }}
{{- range $key, $value := .Values.config }}
  {{ $key }}: {{ $value | toString | b64enc | quote }}
{{- end }}
{{- end }}
---
{{- if or (.Values.userData) (.Values.tlsKey) (.Values.tlsCert) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "drone-autoscaler.fullname" . }}-resources
  labels:
    {{- include "drone-autoscaler.labels" . | nindent 4 }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
type: Opaque
data:
{{- if (.Values.userData) }}
  userData: {{ .Values.userData | b64enc | quote }}
{{- end }}
{{- if (.Values.tlsKey ) }}
  tlsKey: {{ .Values.tlsKey | b64enc | quote }}
{{- end }}
{{- if (.Values.tlsCert ) }}
  tlsCert: {{ .Values.tlsCert | b64enc | quote }}
{{- end }}
{{- end }}
{{- end }}