apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: {{ include "gitMirror.name" . }}-metrics
    helm.sh/chart: {{ include "gitMirror.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
  name: {{ include "gitMirror.name" . }}-metrics
spec:
  replicas: {{ .Values.metrics.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "gitMirror.name" . }}-metrics
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "gitMirror.name" . }}-metrics
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      shareProcessNamespace: true
      containers:
      - name: metrics
        env:
        - name: INFLUX_USER
          valueFrom:
            secretKeyRef:
              name: metrics
              key: INFLUX_USER
        - name: INFLUX_PASS
          valueFrom:
            secretKeyRef:
              name: metrics
              key: INFLUX_PASS
        - name: INFLUX_URL
          valueFrom:
            secretKeyRef:
              name: metrics
              key: INFLUX_URL
        args:
        - rancher-catalog-stats
        - -filepath
        - {{ .Values.catalog_filepath }}
        - -influxurl
        - $(INFLUX_URL)
        - -influxdb
        - catalog
        - -daemon
        - -poll
        - -debug
        - -influxuser
        - $(INFLUX_USER)
        - -influxpass
        - $(INFLUX_PASS)
        image: {{ .Values.metrics.image.repository }}:{{ .Values.metrics.image.tag }}
        imagePullPolicy: {{ .Values.metrics.image.pullPolicy }}
        resources:
{{ toYaml .Values.metrics.resources | indent 8 }}
        volumeMounts:
{{- if .Values.volumeMounts }}
{{ toYaml .Values.volumeMounts | indent 8 }}
{{- end }}
      restartPolicy: Always
      volumes:
{{- if .Values.volumes }}
{{ toYaml .Values.volumes | indent 6 }}
{{- end }}